version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: app_academia
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    academiadb:
        image: mysql:5.7
        restart: always
        container_name: db_academia
        volumes:
            - ../db:/docker-entrypoint-initdb.d
            - academiadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: academia
            MYSQL_USER: local
            MYSQL_PASSWORD: 123456
        command: mysqld --sql_mode=""
        ports:
            - 8984:3306
        networks:
            - laravel

networks:
    laravel:
volumes:
  academiadb:
